@base_url = http://localhost:3000

###
GET {{base_url}}/tasks

###
GET {{base_url}}/tasks/3dacc4b8-2f5a-4902-ae96-0493cce4ae79

###
DELETE {{base_url}}/tasks/6b4e9252-ad03-476e-92fa-0cf2ce9701c0

###
POST {{base_url}}/tasks
Content-Type: application/json

{
    "title": "run",
    "description": "Run 30 minutes each day",
    "status": "pending",
    "priority": "high",
    "dueDate": "2025-10-15",
    "userId": "e0e8b0df-a51c-49b5-a717-d2e1f0487941",
    "categoryId": "cb23e478-fd3c-4032-a47b-d80d71ab8e27"
}

###
POST {{base_url}}/tasks
Content-Type: application/json

{
    "title": "eat healthy",
    "description": "prepare healthier food",
    "status": "pending",
    "priority": "medium",
    "dueDate": "2025-10-17",
    "userId": "9398271d-14f1-457d-afcc-ffb0212addb5",
    "categoryId": "fc33e808-9371-416f-9044-df32e97a831e"
}

###
POST {{base_url}}/tasks
Content-Type: application/json

{
    "title": "read more",
    "description": "read more about programming",
    "dueDate": "2025-10-05",
    "userId": "9398271d-14f1-457d-afcc-ffb0212addb5",
    "categoryId": "fc33e808-9371-416f-9044-df32e97a831e"
}

###
PUT {{base_url}}/tasks/9a753f9f-c340-4221-a99d-b8a5889a9eec
Content-Type: application/json

{
    "title": "eat healthier",
    "description": "prepare healthier food all days",
    "status": "pending",
    "priority": "high",
    "dueDate": "2025-10-15",
    "categoryId": "cb23e478-fd3c-4032-a47b-d80d71ab8e27"
}
