@base_url = http://localhost:3000

###
GET {{base_url}}/tasks?ordeR=Asc&limit=10

###
GET {{base_url}}/tasks/c3c33a31-b26c-44aa-b9bd-549390d962cb

###
DELETE {{base_url}}/tasks/c3c33a31-b26c-44aa-b9bd-549390d962cb

###
POST {{base_url}}/tasks
Content-Type: application/json

{
    "title": "Actualizar dependencias",
    "description": "Run 30 minutes each day",
    "status": "pending",
    "priority": "high",
    "dueDate": "2025-10-15",
    "userId": "e0e8b0df-a51c-49b5-a717-d2e1f0487941",
    "categoryId": "cb23e478-fd3c-4032-a47b-d80d71ab8e27"
}

###
POST {{base_url}}/tasks
Content-Type: application/json

{
    "title": "eat healthy",
    "description": "prepare healthier food",
    "status": "pending",
    "priority": "medium",
    "dueDate": "2025-10-17",
    "userId": "9398271d-14f1-457d-afcc-ffb0212addb5",
    "categoryId": "fc33e808-9371-416f-9044-df32e97a831e"
}

###
POST {{base_url}}/tasks
Content-Type: application/json

{
    "title": "read more",
    "description": "read more about programming",
    "dueDate": "2025-10-05",
    "userId": "9398271d-14f1-457d-afcc-ffb0212addb5",
    "categoryId": "fc33e808-9371-416f-9044-df32e97a831e"
}

###
PUT {{base_url}}/tasks/c3c33a31-b26c-44aa-b9bd-549390d962cb
Content-Type: application/json

{

    "dueDate": "2026-01-01"
}
